# Generated by Django 6.0.2 on 2026-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_code', models.CharField(max_length=45, unique=True)),
                ('display_name', models.CharField(max_length=225)),
                ('react_path', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_route',
                'managed': False,
            },
        ),
    ]
