# Generated by Django 6.0.2 on 2026-02-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_systemroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advicemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advicemaster_id', models.IntegerField(blank=True, null=True)),
                ('advice_name', models.TextField()),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'advicemaster',
                'managed': False,
            },
        ),
    ]
