# Generated by Django 6.0.2 on 2026-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_advicemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=45, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=45, null=True)),
                ('state_code', models.CharField(blank=True, max_length=45, null=True)),
                ('district_code', models.CharField(blank=True, max_length=45, null=True)),
                ('city_code', models.CharField(blank=True, max_length=45, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=45, unique=True)),
                ('department_code', models.CharField(blank=True, max_length=45, null=True)),
                ('designation_code', models.CharField(blank=True, max_length=45, null=True)),
                ('division_code', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_firstname', models.CharField(max_length=100)),
                ('employee_middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_lastname', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, db_comment='1=>Male, 2=>Female, 3=>Other', null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('total_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(db_comment='1=>Existing, 2=>Resigned, 3=>Terminated')),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=45, null=True)),
                ('state_code', models.CharField(blank=True, max_length=45, null=True)),
                ('district_code', models.CharField(blank=True, max_length=45, null=True)),
                ('city_code', models.CharField(blank=True, max_length=45, null=True)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialyearMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financialyear_code', models.CharField(max_length=45, unique=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('status', models.IntegerField()),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financialyear_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsertypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype_code', models.CharField(max_length=45, unique=True)),
                ('usertype_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usertype_master',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Financialyear',
        ),
        migrations.DeleteModel(
            name='Usertype',
        ),
    ]
