# Generated by Django 6.0.2 on 2026-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_complaintmaster_expensesmaster_hospitaldetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=45, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(blank=True, max_length=45, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=45, null=True)),
                ('bank_accountno', models.CharField(blank=True, max_length=45, null=True)),
                ('bank_ddpayableaddress', models.CharField(blank=True, max_length=255, null=True)),
                ('financialyear_code', models.CharField(blank=True, max_length=45, null=True)),
                ('company_code', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bankdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BedAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_code', models.CharField(blank=True, max_length=45, null=True)),
                ('patient_code', models.CharField(blank=True, max_length=45, null=True)),
                ('allotment_timestamp', models.DateTimeField(blank=True, null=True)),
                ('discharge_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bed_allotment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_firstname', models.CharField(max_length=255)),
                ('donor_middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_lastname', models.CharField(max_length=255)),
                ('blood_group_code', models.CharField(max_length=10)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('last_donation_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=1000, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blood_donor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BloodGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_code', models.CharField(max_length=10, unique=True)),
                ('blood_group_name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField()),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField()),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blood_group_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_code', models.CharField(max_length=45, unique=True)),
                ('relation_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relation_master',
                'managed': False,
            },
        ),
    ]
