# Generated by Django 6.0.2 on 2026-02-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_bankdetails_bedallotment_blooddonor_bloodgroupmaster_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bankdetails',
        ),
        migrations.DeleteModel(
            name='BedAllotment',
        ),
        migrations.DeleteModel(
            name='BloodDonor',
        ),
        migrations.DeleteModel(
            name='BloodGroupMaster',
        ),
        migrations.DeleteModel(
            name='RelationMaster',
        ),
    ]
