# Generated by Django 6.0.2 on 2026-02-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_bed_doctor_dsmmaster_habitmaster_hallucinationmaster_and_more'),
        ('backend', '0009_delete_bankdetails_delete_bedallotment_and_more'),
    ]

    operations = [
    ]
