# Generated by Django 6.0.2 on 2026-02-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_merge_20260226_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintMaster',
        ),
        migrations.DeleteModel(
            name='ExpensesMaster',
        ),
        migrations.DeleteModel(
            name='HospitalDetails',
        ),
        migrations.DeleteModel(
            name='MoodHistoryMaster',
        ),
        migrations.DeleteModel(
            name='MseMaster',
        ),
        migrations.DeleteModel(
            name='Noticeboard',
        ),
        migrations.DeleteModel(
            name='ThoughtContentMaster',
        ),
    ]
