# Generated by Django 5.2.10 on 2026-02-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_delete_complaintmaster_delete_expensesmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_code', models.CharField(max_length=45, unique=True)),
                ('complaint_name', models.CharField(max_length=225)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complaint_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_code', models.CharField(max_length=25, unique=True)),
                ('expenses_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, db_comment='1=Active, 0=Inactive', null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expenses_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoodHistoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_history_code', models.CharField(max_length=25, unique=True)),
                ('mood_history_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, db_comment='1=Active, 0=Inactive', null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mood_history_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mse_code', models.CharField(max_length=25, unique=True)),
                ('mse_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, db_comment='1=Active, 0=Inactive', null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mse_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_code', models.CharField(max_length=45, unique=True)),
                ('notice_name', models.CharField(max_length=255)),
                ('notice_description', models.TextField()),
                ('notice_srart_date', models.DateField(blank=True, null=True)),
                ('notice_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, db_comment='1=Active, 0=Inactive', null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'noticeboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThoughtContentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought_content_code', models.CharField(max_length=25, unique=True)),
                ('thought_content_name', models.CharField(max_length=100)),
                ('status', models.IntegerField(blank=True, db_comment='1=Active, 0=Inactive', null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thought_content_master',
                'managed': False,
            },
        ),
    ]
