# Generated by Django 6.0.2 on 2026-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_aadhaarverificationrequests_bankdetails_bedallotment_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bed',
            table='bed',
        ),
        migrations.AlterModelTable(
            name='habitmaster',
            table='habit_master',
        ),
        migrations.AlterModelTable(
            name='hallucinationmaster',
            table='hallucination_master',
        ),
        migrations.AlterModelTable(
            name='historymaster',
            table='history_master',
        ),
        migrations.AlterModelTable(
            name='roomtypemaster',
            table='room_type_master',
        ),
    ]
