# Generated by Django 6.0.2 on 2026-03-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_complaintmaster_expensesmaster_moodhistorymaster_and_more'),
        ('backend', '0013_alter_bed_table_alter_habitmaster_table_and_more'),
    ]

    operations = [
    ]
