# Generated by Django 6.0.2 on 2026-03-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_merge_20260303_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('hospital_code', models.CharField(max_length=45)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_renew_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('informant', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentTypeMaster',
            fields=[
                ('appointment_type_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('appointment_type_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointment_type_master',
                'managed': False,
            },
        ),
    ]
