# Generated by Django 6.0.2 on 2026-03-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
