# Generated by Django 6.0.2 on 2026-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_account_designation_division_ect_followup_opdbilling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_summary_code', models.CharField(max_length=45, unique=True)),
                ('summary_date', models.DateField(blank=True, null=True)),
                ('age_at_discharge', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address_snapshot', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('visit_type', models.CharField(blank=True, db_comment='IPD or OPD', max_length=10, null=True)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('mse', models.TextField(blank=True, db_comment='Mental State Examination', null=True)),
                ('investigations', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_given', models.TextField(blank=True, null=True)),
                ('advice_on_discharge', models.TextField(blank=True, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discharge_summary',
                'managed': False,
            },
        ),
    ]
