# Generated by Django 5.2.7 on 2026-03-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_dischargesummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttypemaster',
            options={},
        ),
    ]
