# Generated by Django 6.0.2 on 2026-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_dischargesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, db_comment='1=Active, 0=Inactive', null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
    ]
