# Generated by Django 6.0.2 on 2026-03-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_appointmenttypemaster_options'),
        ('backend', '0020_branch'),
    ]

    operations = [
    ]
