# Generated by Django 6.0.2 on 2026-03-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_merge_20260309_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttypemaster',
            options={'managed': False},
        ),
    ]
