# Generated by Django 6.0.2 on 2026-03-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_appointmenttypemaster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opdcasesheet',
            options={'managed': False},
        ),
    ]
