# Generated by Django 6.0.2 on 2026-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_opdcasesheet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=30, unique=True)),
                ('currency_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timezones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_code', models.CharField(max_length=45, unique=True)),
                ('timezone_name', models.CharField(max_length=100)),
                ('offset', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=50)),
                ('createdon', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timezones',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='opdcasesheet',
            table='opd_casesheet',
        ),
    ]
